### PR TITLE
Create and initailize the project #10 & Design logo for the project #8 

### PR DESCRIPTION
**Pull request by H-SM**
here's my PR, hope you like the changes over it 
(●'◡'●) ^_^

### CODE REVIEW

**Comment by H-SM** [comment]
ayo, I solved up the 2 issues #10 and #8 in this PR only, I didn't want to make a sperate branch for it as it would have gone against what is mentioned over the documentation

**Comment by bhavika2502** [comment]
As for the logo, I would suggest making it more understandable that it is based on vaccines etc. 
As for names I came up with OPEN-Vaccinfo or OPEN-Vaccifo, if you wish to accommodate these

**Comment by H-SM** [comment]
@bhavika2502 for the logo firstly, ill try making up a new one related to the vaccine & ill name it "OPEN-Vaccinfo", BUT, for the other issue all the points youv'e mentioned are there, there is a running back-end with express, node and even a mongo localhost connection and a react front-end, the only thing I did differently there is naming front-end as "client" & back-end as "server", that's all

**Comment by bhavika2502** [comment]
Hey! So I would suggest you to rename the folder structure a bit so everyone can understand and contribute easily.

**Comment by H-SM** [comment]
ayo @bhavika2502 , I did all the changes here ...  q(≧▽≦q)

**Comment by bhavika2502** [comment]
Good work! @H-SM

**Pull request merged**
