### PR TITLE
Logo

### PR DESCRIPTION
**Pull request by priii-25**

### CODE REVIEW

**Comment by bhavika2502** [comment]
Hi, try coming up with a name for this project and insert it into the logo

**Comment by bhavika2502** [comment]
I thought of "OPEN-Vaccinfo" or "OPEN-Vaccifo" if you wish to go forward with any of these

**Comment by priii-25** [comment]
sure, what about shotsecure, immunova, immunicare,VaxGuardian?

**Comment by bhavika2502** [comment]
Hey! You can work on a new issue as logo has been made and updated

**Pull request closed without merging**
